apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: xium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      imagePullSecrets:
        - name: dockerio-creds
      containers:
      - name: sample
        image: xiumjp/mfe-sample:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: xium
spec:
  type: NodePort
  selector:
    app: sample
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
