apiVersion: apps/v1
kind: Deployment
metadata:
  name: recurring-billing-form-deployment
  namespace: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recurring-billing-form
  template:
    metadata:
      labels:
        app: recurring-billing-form
    spec:
      imagePullSecrets:
        - name: dockerio-creds
      containers:
      - name: recurring-billing-form
        image: xiumjp/mfe-recurring-billing-form:latest
        env:

        # STRIPE
        - name: VITE_STRIPE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-secret
              key: STRIPE_PUBLIC_KEY
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: recurring-billing-form-service
  namespace: payment
spec:
  type: NodePort
  selector:
    app: recurring-billing-form
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
